# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spectrometer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spectrometer
    pod 'Charts/Realm'
    pod 'Zip'
    pod "PlainPing"
    pod "Pulsator"

  target 'SpectrometerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
