# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spectrometer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'

  # Pods for Spectrometer
    pod 'Charts'
    pod 'Zip'
    pod 'PlainPing'
    pod 'Pulsator'
    pod 'FontAwesome.swift'

  target 'SpectrometerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end